// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReservaSalaReuniones.En
{
    public partial class Roles
    {
        public Roles()
        {
            RolUsuario = new HashSet<RolUsuario>();
        }

        [Key]
        [Column("Id_Rol")]
        public int IdRol { get; set; }
        [Required]
        [MaxLength(100)]
        public string NombreRol { get; set; }
        public bool Estado { get; set; }

        [InverseProperty("IdRolNavigation")]
        public virtual ICollection<RolUsuario> RolUsuario { get; set; }
    }
}