// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReservaSalaReuniones.En
{
    [Table("Rol_Usuario")]
    public partial class RolUsuario
    {
        [Key]
        [Column("Id_Rol_Usuario")]
        public int IdRolUsuario { get; set; }
        [Column("Id_Usuario")]
        public int IdUsuario { get; set; }
        [Column("Id_Rol")]
        public int IdRol { get; set; }

        [ForeignKey(nameof(IdRol))]
        [InverseProperty(nameof(Roles.RolUsuario))]
        public virtual Roles IdRolNavigation { get; set; }
        [ForeignKey(nameof(IdUsuario))]
        [InverseProperty(nameof(Usuario.RolUsuario))]
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}