// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReservaSalaReuniones.En
{
    public partial class Usuario
    {
        public Usuario()
        {
            Reserva = new HashSet<Reserva>();
            RolUsuario = new HashSet<RolUsuario>();
        }

        [Key]
        [Column("Id_Usuario")]
        public int IdUsuario { get; set; }
        [Required]
        [Column("Nick_Name")]
        [StringLength(50)]
        public string NickName { get; set; }
        [Required]
        [Column("Nombre_Usuario")]
        [StringLength(100)]
        public string NombreUsuario { get; set; }
        [Required]
        [StringLength(200)]
        public string Email { get; set; }
        [Required]
        [StringLength(200)]
        public string Password { get; set; }

        public bool Estado { get; set; }

        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Reserva> Reserva { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<RolUsuario> RolUsuario { get; set; }
    }
}